"""empty message

Revision ID: 86aae3d8584a
Revises: f64824eb63a2
Create Date: 2018-03-16 01:42:07.279521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86aae3d8584a'
down_revision = 'f64824eb63a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jingfen_products', sa.Column('prize_amout', sa.Float(), nullable=False))
    op.drop_column('jingfen_products', 'prize_amtout')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jingfen_products', sa.Column('prize_amtout', mysql.DECIMAL(precision=8, scale=4), nullable=False))
    op.drop_column('jingfen_products', 'prize_amout')
    # ### end Alembic commands ###
