"""empty message

Revision ID: 8cd4462af38c
Revises: 0b8a90a03f50
Create Date: 2018-03-21 02:59:07.924158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd4462af38c'
down_revision = '0b8a90a03f50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jingfen_products', sa.Column('group_price', sa.Float(), nullable=True))
    op.add_column('jingfen_products', sa.Column('group_prson_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jingfen_products', 'group_prson_number')
    op.drop_column('jingfen_products', 'group_price')
    # ### end Alembic commands ###
