"""empty message

Revision ID: f64824eb63a2
Revises: 19da206f08da
Create Date: 2018-03-15 00:25:03.647146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f64824eb63a2'
down_revision = '19da206f08da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jingfen_products', sa.Column('good_come', sa.Integer(), nullable=True))
    op.alter_column('jingfen_products', 'bonus_rate',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               nullable=False)
    op.alter_column('jingfen_products', 'prize_amout',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               nullable=False)
    op.drop_index('ix_jingfen_products_jd_uid', table_name='jingfen_products')
    op.drop_column('jingfen_products', 'jd_uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jingfen_products', sa.Column('jd_uid', mysql.VARCHAR(length=128), nullable=True))
    op.create_index('ix_jingfen_products_jd_uid', 'jingfen_products', ['jd_uid'], unique=True)
    op.alter_column('jingfen_products', 'prize_amout',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               nullable=True)
    op.alter_column('jingfen_products', 'bonus_rate',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               nullable=True)
    op.drop_column('jingfen_products', 'good_come')
    # ### end Alembic commands ###
